# -*- mode: python -*-
# vi: set ft=python :

import os
import platform
import shlex
import subprocess
from pathlib import Path

import aw_core
import flask_restx

# PyInstaller injects SPECPATH (directory containing the spec file).
# Do not rely on __file__ (not present in spec exec context).
BASE_DIR = Path(SPECPATH)


def build_analysis(name, location, binaries=[], datas=[], hiddenimports=[]):
    name_py = name.replace("-", "_")
    location_candidates = [
        location / f"{name_py}/__main__.py",
        location / f"src/{name_py}/__main__.py",
    ]
    try:
        location = next(p for p in location_candidates if p.exists())
    except StopIteration:
        raise Exception(f"Could not find {name} location from {location_candidates}")

    return Analysis(
        [location],
        pathex=[],
        binaries=binaries,
        datas=datas,
        hiddenimports=hiddenimports,
        hookspath=[],
        runtime_hooks=[],
        excludes=[],
        win_no_prefer_redirects=False,
        win_private_assemblies=False,
    )


def build_collect(analysis, name, console=True, upx=True):
    """Used to build the COLLECT statements for each module.

    On Windows, UPX-compressed ``cryptography`` Rust extension (``_rust.pyd``) often fails at
    runtime with: DLL load failed ... The specified procedure could not be found.
    Pass ``upx=False`` for bundles that ship ``cryptography`` (e.g. aw-server + aw_client ILS).
    """
    pyz = PYZ(analysis.pure, analysis.zipped_data)
    exe = EXE(
        pyz,
        analysis.scripts,
        exclude_binaries=True,
        name=name,
        debug=False,
        strip=False,
        upx=upx,
        console=console,
        contents_directory=".",
        entitlements_file=entitlements_file,
        codesign_identity=codesign_identity,
    )
    return COLLECT(
        exe,
        analysis.binaries,
        analysis.zipfiles,
        analysis.datas,
        strip=False,
        upx=upx,
        name=name,
    )


# App version (prefer explicit env var set by build script).
# Avoid calling git here (mono-repo builds may not have git metadata and can leak "fatal:" into Info.plist).
app_version = os.environ.get("ILS_APP_VERSION", "").strip()
if not app_version:
    try:
        app_version = (BASE_DIR / "ILS_VERSION").read_text(encoding="utf8").strip()
    except Exception:
        app_version = "0.0.0"
print("bundling InsightLoggerSystem version " + app_version)

# Get entitlements and codesign identity
entitlements_file = BASE_DIR / "scripts" / "package" / "entitlements.plist"
codesign_identity = os.environ.get("APPLE_PERSONALID", "").strip()
if not codesign_identity:
    print("Environment variable APPLE_PERSONALID not set. Releases won't be signed.")

aw_core_path = Path(os.path.dirname(aw_core.__file__))
restx_path = Path(os.path.dirname(flask_restx.__file__))

aws_location = BASE_DIR / "aw-server"
aw_qt_location = BASE_DIR / "aw-qt"
aww_location = BASE_DIR / "aw-watcher-window"

if platform.system() == "Darwin":
    icon = aw_qt_location / "media/logo/logo.icns"
else:
    icon = aw_qt_location / "media/logo/logo.ico"

# Auto-update companion (macOS only at the moment). The Windows ils-updater.exe
# is produced by a separate PyInstaller step in build-window.sh and bundled by
# the NSIS installer, not by this spec.
updater_datas = []
updater_script = BASE_DIR / "scripts" / "updater" / "ils-updater.sh"
if platform.system() == "Darwin" and updater_script.exists():
    updater_datas.append((str(updater_script), "."))

# Bundle the ILS_VERSION file so the About dialog and the auto-update check
# resolve the running app's version at runtime.
ils_version_file = BASE_DIR / "ILS_VERSION"
version_datas = []
if ils_version_file.exists():
    version_datas.append((str(ils_version_file), "."))

aw_qt_a = build_analysis(
    "aw-qt",
    aw_qt_location,
    binaries=[],
    datas=[
        (aw_qt_location / "resources/aw-qt.desktop", "aw_qt/resources"),
        (aw_qt_location / "media", "aw_qt/media"),
        *updater_datas,
        *version_datas,
    ],
    # PyInstaller can't reliably detect these runtime imports.
    hiddenimports=[
        "aw_qt.trayicon",
        "aw_qt.macos_launch_agent",
        "aw_qt.update_manager",
        "aw_qt.version_info",
        "aw_core.update_shutdown",
        "aw_core.win_process",
    ],
)
aw_server_a = build_analysis(
    "aw-server",
    aws_location,
    datas=[
        (aws_location / "aw_server/static", "aw_server/static"),
        # Bundled runtime env file (generated by build-macos.sh)
        (BASE_DIR / "ils.env", "aw_server"),
        # Ensure aw-client token store is available in packaged app
        (BASE_DIR / "aw-client" / "aw_client", "aw_client"),
        (restx_path / "templates", "flask_restx/templates"),
        (restx_path / "static", "flask_restx/static"),
        (aw_core_path / "schemas", "aw_core/schemas"),
        # ILS_VERSION lets the auto-update cron know what version we are
        # running so it can ask the backend whether there is a newer one.
        *version_datas,
    ],
    hiddenimports=[
        # Imported dynamically at runtime
        "aw_client",
        "aw_client.ils_token_store",
        "aw_core.retention",
    ],
)
aw_watcher_window_a = build_analysis(
    "aw_watcher_window",
    aww_location,
    binaries=(
        [
            (
                aww_location / "aw_watcher_window/aw-watcher-window-macos",
                "aw_watcher_window",
            )
        ]
        if platform.system() == "Darwin"
        else []
    ),
    datas=[
        (aww_location / "aw_watcher_window/printAppStatus.jxa", "aw_watcher_window")
    ],
)

# https://pythonhosted.org/PyInstaller/spec-files.html#multipackage-bundles
# MERGE takes a bit weird arguments, it wants tuples which consists of
# the analysis paired with the script name and the bin name
merge_args = [
    (aw_server_a, "aw-server", "aw-server"),
    (aw_qt_a, "aw-qt", "aw-qt"),
    (aw_watcher_window_a, "aw-watcher-window", "aw-watcher-window"),
]

MERGE(*merge_args)


aws_coll = build_collect(aw_server_a, "aw-server")

# aw-watcher-window
aww_coll = build_collect(aw_watcher_window_a, "aw-watcher-window")

# aw-qt
awq_coll = build_collect(
    aw_qt_a,
    "aw-qt",
    console=False if platform.system() == "Windows" else True,
)


if platform.system() == "Darwin":
    bundle_args = [
        awq_coll,
        aws_coll,
        aww_coll,
    ]
    
    app = BUNDLE(
        *bundle_args,
        name="InsightLoggerSystem.app",
        icon=icon,
        bundle_identifier="net.ils.InsightLoggerSystem",
        version=app_version,
        info_plist={
            "NSPrincipalClass": "NSApplication",
            "CFBundleName": "InsightLoggerSystem",
            "CFBundleDisplayName": "InsightLoggerSystem",
            "CFBundleExecutable": "MacOS/aw-qt",
            "CFBundleIconFile": "logo.icns",
            "NSAppleEventsUsageDescription": "Please grant access to use Apple Events",
            "CFBundleVersion": app_version,
            "CFBundleShortVersionString": app_version,
        },
    )
